import { CONFIG } from "./config.js";

export const appState = {
  version: null,
  selectedMaterial: "flower",
  handVisible: false,
  indexPoint: null,
  thumbPoint: null,
  pinchRatio: null,
  isPinching: false,
  previousPinching: false,
  cameraVisible: false,
  hoveredButtonId: null,
  hoverStartTime: null,
  lastButtonSelectTime: 0,
  clickedButtonId: null,
  clickedButtonAt: 0,
  controlsVisible: true,
  lastControlsInteractionAt: 0,
  isFullscreen: false,
  threeEnabled: CONFIG.three.enabledByDefault,
  threeAvailable: true,
  threeReady: false,
  threeStats: null,
  threeWarning: null,
  debug: CONFIG.debug,
  mirror: CONFIG.mirrorCamera,
  fps: 0,
  hasStrokes: false,
  mouseMode: false,
  mouseDown: false,
  pointerDebug: null,
  trackerDebug: null,
  status: "初始化中...",
  error: null,
  runtimeWarning: null
};
